runtime: python27
api_version: 1
threadsafe: true
skip_files:
- (^node_modules/.*)
- (^.git/.*)

handlers:

- url: /rs/static/js/(.*)
  static_files: static/js/\1
  expiration: "1d"
  upload: static/js/(.*)
  secure: always

- url: /rs/static/images/(.*)
  static_files: static/images/\1
  expiration: "1d"
  upload: static/images/(.*)
  secure: always

- url: /rs/(.*)
  script: main.app
  secure: always

- url: /rs
  script: redirector.app
  secure: always

- url: /
  script: redirector.app
  secure: always


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
